import { Action } from '../Action';
import { ACTS } from './Acts';
import {
  FREE_POSITION,
  ENEMY_AT_POSITION,
  FRIEND_AT_POSITION,
  CLEAR_PATH,
  IS_NO_KING,
  ALWAYS,
} from '../conditions/Conditions';

export const ACTIONS = {
  MOVE_TO_FREE_POSITION: new Action(FREE_POSITION, ACTS.MOVE_OR_ATTACK, 'F'),
  MOVE_TO_ENEMY_POSITION: new Action(ENEMY_AT_POSITION, ACTS.MOVE_OR_ATTACK, 'E'),
  MOVE_OR_ATTACK_ACTION: new Action(ENEMY_AT_POSITION.OR(FREE_POSITION), ACTS.MOVE_OR_ATTACK, 'X'),
  WALK_AND_MOVE_OR_ATTACK: new Action(CLEAR_PATH.AND(ENEMY_AT_POSITION.OR(FREE_POSITION)), ACTS.MOVE_OR_ATTACK, 'M'),
  SWAP_POSITIONS_ACTION: new Action(FRIEND_AT_POSITION.AND(FREE_POSITION.NOT()), ACTS.SWAP_POSITIONS, 'S'),
  RUSH_ACTION: new Action(ALWAYS, ACTS.RUSH_ACT, 'R'),
  CROSS_ATTACK_ACTION: new Action(FREE_POSITION, ACTS.CROSS_ATTACK_ACT, 'C'),
  EXPLOSION_ATTACK_ACTION: new Action(FREE_POSITION, ACTS.EXPLODE_ACT, 'Y'),
  ZOMBIE_ATTACK_ACTION: new Action(ENEMY_AT_POSITION, ACTS.ZOMBIE_ATTACK_ACT, 'Z'),
  RANGE_ATTACK_ACTION: new Action(ENEMY_AT_POSITION.AND(CLEAR_PATH), ACTS.RANGE_ATTACK_ACT, 'A'),
  CONVERT_ACTION: new Action(ENEMY_AT_POSITION.AND(IS_NO_KING), ACTS.CONVERT_ACT, 'Q'),
  LEGION_ATTACK_ACTION: new Action(ENEMY_AT_POSITION.OR(FREE_POSITION), ACTS.LEGION_ATTACK_ACT, 'L'),
} as const;

export function getActionBySymbol(symbol: string): Action | null {
  for (const action of Object.values(ACTIONS)) {
    if (action.symbol === symbol) return action;
  }
  return null;
}
